-- MySQL Script generated by MySQL Workbench
-- Wed Mar 23 15:14:40 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ProyectoFactura
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ProyectoFactura
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ProyectoFactura` DEFAULT CHARACTER SET utf8 ;
USE `ProyectoFactura` ;

-- -----------------------------------------------------
-- Table `ProyectoFactura`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoFactura`.`usuario` (
  `Codigo` VARCHAR(15) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Rol` VARCHAR(15) NULL,
  `Clave` VARCHAR(45) NULL,
  `EstaActivo` VARCHAR(45) NULL,
  `usuariocol` TINYINT NULL,
  PRIMARY KEY (`Codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoFactura`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoFactura`.`producto` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Codigo` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(45) NULL,
  `Precio` DECIMAL(18,2) NULL,
  `Existencia` INT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
